### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by simonbyrne** [climate-machine/Solus.jl#3]
# Functionality
- [ ] EKI
- [ ] higher-level interface for NEKI
- [ ] Gaussian process interpolation
  - Can we use https://github.com/STOR-i/GaussianProcesses.jl or do we need to write our own?
- [ ] MCMC functionality (@glwagner, @sandreza)
  - [ ] Random-walk MH
  - [ ] Slice sampling
  - [ ] HMC (https://github.com/tpapp/DynamicHMC.jl)
- [ ] Experimental design?
- [ ] Multi-fidelity (@odunbar)

# Test/Examples
- [ ] Linear case (@agarbuno)
  - check it converges to the correct distribution
- [ ] Lorenz examples (@dburov190)
- [ ] Elliptic / Darcy flow PDE (@agarbuno)
- [ ] Simple MCMC examples
 - Gaussian
 - heavy tail
 - Gaussian mixture
 - Double well
- [ ] Single column model
  - Can compare direct MCMC with NEKI/GP approximation

For next meeting:
- Lorenz model / GP (@dburov190 )
- NEKI/EKI with simple examples (@agarbuno @odunbar )
- Single column model / MCMC (@glwagner @sandreza)

**Comment by dburov190** [comment]
I've marked "Gaussian processes" done for now; the implementation is in GPR.jl. It uses ScikitLearn.jl, which is quite bulky and ugly, but good enough for now. Planning to switch to GaussianProcesses.jl in the future.
